<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1018671" started-at="2020-05-09T10:14:50 IST" finished-at="2020-05-09T10:31:49 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1018671" started-at="2020-05-09T10:14:50 IST" finished-at="2020-05-09T10:31:49 IST">
      <class name="com.atcost.Testcase.QuestionTest">
        <test-method status="PASS" signature="first()[pri:0, instance:com.atcost.Testcase.QuestionTest@5f282abb]" name="first" is-config="true" duration-ms="50484" started-at="2020-05-09T10:14:50 IST" finished-at="2020-05-09T10:15:41 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- first -->
        <test-method status="FAIL" signature="Question3()[pri:0, instance:com.atcost.Testcase.QuestionTest@5f282abb]" name="Question3" duration-ms="962892" started-at="2020-05-09T10:15:41 IST" finished-at="2020-05-09T10:31:44 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.UnifyPage.UniversityPage.section(UniversityPage.java:68)
at com.atcost.Testcase.QuestionTest.Question3(QuestionTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1255)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Question3 -->
        <test-method status="PASS" signature="close()[pri:0, instance:com.atcost.Testcase.QuestionTest@5f282abb]" name="close" is-config="true" duration-ms="20" started-at="2020-05-09T10:31:48 IST" finished-at="2020-05-09T10:31:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- com.atcost.Testcase.QuestionTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
